
FROM node:22.17.1

ENV NODE_VERSION 22.17.1

# 安装Ruby环境和必要的依赖
RUN apt-get update && apt-get install -y \
    ruby \
    ruby-dev \
    build-essential \
    git \
    curl \
    libssl-dev \
    libreadline-dev \
    zlib1g-dev \
    libsqlite3-dev \
    && rm -rf /var/lib/apt/lists/*

# 安装Ruby gems
RUN gem install hitimes -v 2.0.0
RUN gem install zendesk_apps_tools
 