FROM node:22.17.1
ENV NODE_VERSION 22.17.1
RUN node --version

ENV YARN_VERSION berry 
RUN yarn set version $YARN_VERSION
RUN yarn --version

RUN apt-get update && apt-get install zip
#RUN apk update && apk add zip git bash
