FROM node:20.10 AS nodejs

ENV NODE_VERSION 20.10

RUN node --version \
    && npm version && git --version


RUN which diff2html || npm install -g -ignore-scripts  @nullcc/diff2html-cli || true
RUN which istanbul-merge || npm install -g -ignore-scripts  istanbul-merge || true
RUN npm i -g typescript-language-server && npm install -g typescript && npm install  -g @nullcc/sdet-cli
RUN npm i -ignore-scripts -g lcov-result-merger