
FROM node:22.17.1

ENV NODE_VERSION 22.17.1

# 安装Ruby环境
RUN apt-get update && apt-get install -y \
    ruby \
    ruby-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# 安装Ruby gems
RUN gem install hitimes -v 2.0.0
RUN gem install zendesk_apps_tools
 