name: Build Image

on:
  pull_request:
    branches:
      - main
    paths:
      # '*' matches any character except '/'
      - 'images/*'
      - '.github/workflows/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build Imag:gsuite-cli
        run: |
          cd images
          IMAGE_NAME=ringcentral/int-gsuite-cli
          docker build -t ${IMAGE_NAME} -f Dockerfile.gsuite-cli .
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest"

      - name: Build Imag:webstore-cli
        run: |
          cd images
          IMAGE_NAME=ringcentral/int-webstore-cli
          VERSION="$(awk -F '[@]'  '/chrome-webstore-upload-cli/ {print $2}' Dockerfile.webstore-cli)"
          docker build -t ${IMAGE_NAME} -f Dockerfile.webstore-cli .
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest"   
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${VERSION}"   

      - name: Build Imag:node-zip
        run: |
          cd images
          IMAGE_NAME=ringcentral/int-node-zip 
          docker build -t ${IMAGE_NAME} -f Dockerfile.node .
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest"

      - name: Build Imag:sentry-cli
        run: |
          cd images
          IMAGE_NAME=ringcentral/sentry-cli 
          docker build -t ${IMAGE_NAME} -f Dockerfile.sentry-cli .
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest"

      - name: Build Imag:int-node-awscli
        run: |
          cd images
          IMAGE_NAME=ringcentral/int-node-awscli
          docker build -t ${IMAGE_NAME} -f Dockerfile.node.awscli .
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest"

      - name: Build Imag:zendesk-cli
        run: |
          cd images
          IMAGE_NAME=ringcentral/int-zendesk-cli
          docker build -t ${IMAGE_NAME} -f Dockerfile.zendesk-cli .
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest"

      - name: Build Imag:node-sdet-cli
        run: |
          cd images
          IMAGE_NAME=ringcentral/node-sdet-cli
          docker build -t ${IMAGE_NAME} -f Dockerfile.node-sdet-cli .
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest"

      - name: Build Imag:sonarscan
        run: |
          cd images
          IMAGE_NAME=ringcentral/sonarscan
          docker build -t ${IMAGE_NAME} -f Dockerfile.sonarscan .
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest"
